[config.wallpaper]
command = "awww"

[templates.niri]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar-colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.waybar-niri-Win11Like]
input_path = '~/.config/matugen/templates/waybar-colors.css'
output_path = '~/.config/waybar-niri-Win11Like/colors.css'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/matugen.conf'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel-colors.ini'
output_path = '~/.config/fuzzel/colors.ini'

